baseURL = 'https://melexandra.com'
languageCode = 'sv-se'
title = 'Melker och Alexandra gifter sig'
theme = 'story'
copyright = 'Melexandra'

[markup.goldmark.renderer]
unsafe = true # Allow HTML

[params]
  header_image = 'header.jpeg'
  image_404 = 'blad.jpg'
  title_404 = 'Hoppsan hejsan den sidan finns inte'
