baseURL = 'https://melexandra.com'
languageCode = 'sv-se'
title = 'Melexandra'
theme = 'story'
copyright = 'Melexandra'

[markup.goldmark.renderer]
unsafe = true # Allow HTML

[Params]
  favicon = false
